### ISSUE TITLE
Avoid the ManuallyDrop hack

### ISSUE THREAD

**Issue by cole-miller** [sndjvu/workspace#18]

**Comment by cole-miller** [comment]
I found that the same drop check issue also affects more complex decoding loops when using `bzz::dec`, so whatever the solution is here will have to apply to that as well.

**Comment by cole-miller** [comment]
This is addressed by 21cd775264b50d222a22e9d389fedfa7a1f40cc6: we keep using the hack, but encapsulate it in a couple of generic functions so that consumers of sndjvu_codec have a way to write custom compression/decompression loops without weird workarounds. (The primitive state machine is still exposed for consumers that need maximum flexibility.)

**Comment by cole-miller** [comment]
I've removed the generic functions in 92c79eebc2f6a583aae9301a8468801e40a1ed8c. Maybe I'll find a more satisfactory workaround in the future that's worth exposing from sndjvu_codec.

**Comment by WaffleLapkin** [comment]
fyi https://github.com/rust-lang/rust/issues/70919 was fixed, it does not reproduce anymore.

**Comment by cole-miller** [comment]
Done in 6a6aec079b0fe2c41c3ec21319c7698c25e91509
